# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[ 9 11  5  6 15]
 [ 9 13 19 10 10]
 [11  3 17  7  2]
 [ 9 13 10 10 12]
 [16 10 20  6 17]]
Modified array:
[[ 9 11  1  6 15]
 [ 9 13  1 10 10]
 [11  3  1  7  2]
 [ 9 13  1 10 12]
 [16 10  1  6 17]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6, 6))
print("Original array:")
print(array)

# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[20 10 16 19 13]
 [ 1  7  9  4  4]
 [18 20 16 14 15]
 [17  3  4  3 17]
 [ 2 15  2 12 18]]
Border elements:
[20 10 16 19 13  2 15  2 12 18  1 18 17  4 15 17]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 9  1  4  1]
 [ 7  8  7  4]
 [ 9 10  5  5]]
Array 2:
[[6 5 3 6]
 [9 5 1 6]
 [9 9 5 9]]
Element-wise addition:
[[15  6  7  7]
 [16 13  8 10]
 [18 19 10 14]]
Element-wise subtraction:
[[ 3 -4  1 -5]
 [-2  3  6 -2]
 [ 0  1  0 -4]]
Element-wise multiplication:
[[54  5 12  6]
 [63 40  7 24]
 [81 90 25 45]]
Element-wise division:
[[1.5        0.2        1.33333333 0.16666667]
 [0.77777778 1.6        7.         0.66666667]
 [1.         1.11111111 1.         0.55555556]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [7]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[12  8  4  7 15]
 [ 5  1  1  7 18]
 [ 7 20 11 18 17]
 [ 3 10 15 19 17]
 [ 9  5  9  4  4]]
Mean: 9.84
Median: 9.0
Standard Deviation: 5.8765976551062264
Variance: 34.5344


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [9]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[5 9 8]
 [7 4 5]
 [6 8 8]]
1D array:
[2 3 3]
Resulting array:
[[ 7 12 11]
 [ 9  7  8]
 [ 8 11 11]]


In [16]:
print(column_array)
column_array[:, np.newaxis]

[1 1 8 4]


array([[1],
       [1],
       [8],
       [4]])

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [23]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
column_array = column_array[:, np.newaxis]
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array
print("Resulting array:")
print(result)

Original array:
[[5 1 8 3]
 [2 8 6 7]
 [6 7 8 1]
 [2 7 8 3]]
1D array:
[[1]
 [1]
 [8]
 [7]]
Resulting array:
[[ 4  0  7  2]
 [ 1  7  5  6]
 [-2 -1  0 -7]
 [-5  0  1 -4]]


In [20]:
array = np.random.randint(1, 11, size=(3, 4))
array = array.transpose()
column_array = np.random.randint(1, 11, size=(4))
column_array = column_array.reshape(4,1)
print("Original array:")
print(array)
print("1D array:")
print(column_array)

array.transpose()


# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array
print("Resulting array:")
print(result)

Original array:
[[ 9  3  5]
 [ 5  1 10]
 [ 8  3  1]
 [ 6  4  3]]
1D array:
[[9]
 [3]
 [7]
 [9]]
Resulting array:
[[ 0 -6 -4]
 [ 2 -2  7]
 [ 1 -4 -6]
 [-3 -5 -6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [24]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[10  1  4]
 [ 3  9  9]
 [ 7  9  5]]
Determinant: -456.00000000000017
Inverse:
[[ 0.07894737 -0.06798246  0.05921053]
 [-0.10526316 -0.04824561  0.17105263]
 [ 0.07894737  0.18201754 -0.19078947]]
Eigenvalues: [18.84085335  8.13447422 -2.97532757]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [25]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[3 1 7]
 [2 8 7]]
Array 2:
[[9 7]
 [2 3]
 [6 2]]
Matrix multiplication result:
[[71 38]
 [76 52]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [26]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [31]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

print("array.shape", array.shape)

print("array.size", array.size)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

print("flattened_array.shape:")
print(flattened_array.shape)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[ 6 19  4  7  8]
 [ 8 13  5  6 19]
 [ 9 15  9 14 15]
 [ 4  9 18  1  3]
 [10 18  5 15  3]]
array.shape (5, 5)
array.size 25
Flattened array:
[ 6 19  4  7  8  8 13  5  6 19  9 15  9 14 15  4  9 18  1  3 10 18  5 15
  3]
flattened_array.shape:
(25,)
Reshaped array:
[[ 6 19  4  7  8]
 [ 8 13  5  6 19]
 [ 9 15  9 14 15]
 [ 4  9 18  1  3]
 [10 18  5 15  3]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [33]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[11 14 14 11  5]
 [12 15 18  5 20]
 [ 7  6 15  1  4]
 [19  4 15 13 13]
 [12 18  9  2  4]]
Corner elements:
[11  5 12  4]


In [38]:
#1st take 1st row 2 times and last row 2 times
array[[0, 0, -1, -1]]

array([[11, 14, 14, 11,  5],
       [11, 14, 14, 11,  5],
       [12, 18,  9,  2,  4],
       [12, 18,  9,  2,  4]])

In [41]:
#then take 1st element of 1st row, last element of 2nd row, then again 1st element of 3rd and last element of 4th row
array[[0, 0, -1, -1],[0,-1,0,-1]]

array([11,  5, 12,  4])

In [35]:
array[[0, -1, 0, -1]]

array([[11, 14, 14, 11,  5],
       [12, 18,  9,  2,  4],
       [11, 14, 14, 11,  5],
       [12, 18,  9,  2,  4]])

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [43]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[15 13  8  3]
 [17 14  3  6]
 [14  8 10  6]
 [ 6 10  5 19]]
Modified array:
[[10 10  8  3]
 [10 10  3  6]
 [10  8 10  6]
 [ 6 10  5 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [44]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [45]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [48]:
data['x']

array([1, 3, 5], dtype=int32)

In [49]:
data['x'][:, np.newaxis]

array([[1],
       [3],
       [5]], dtype=int32)

In [47]:
data['x'][:, np.newaxis] - data['x']

array([[ 0, -2, -4],
       [ 2,  0, -2],
       [ 4,  2,  0]], dtype=int32)

In [50]:
(data['x'][:, np.newaxis] - data['x'])**2

array([[ 0,  4, 16],
       [ 4,  0,  4],
       [16,  4,  0]], dtype=int32)

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [60]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[10  3 17 15]
 [14  9  5  1]
 [18  7 19 18]
 [10  9  6 11]]
Masked array:
[[10 3 -- --]
 [-- 9 5 1]
 [-- 7 -- --]
 [10 9 6 --]]
Sum of unmasked elements: 60


In [61]:
array[array>10] = 0

In [63]:
array.sum()

np.int64(60)

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [64]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[15 19 15]
 [ 3 14 15]
 [13  1 20]]
Masked array:
[[-- 19 15]
 [3 -- 15]
 [13 1 --]]
Modified masked array:
[[11 19 15]
 [ 3 11 15]
 [13  1 11]]
